### ISSUE TITLE
Errors on the code os.mkdir

### ISSUE THREAD

**Issue by Abdesol** [shravanasati/pyscreenrec#2]
Hello, I need to show you one error I am facing.
the error shows as below:
```
File "C:\Users\Abdesol\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyscreenrec\__init__.py", line 29, in __init__
    os.mkdir(self.screenshot_folder)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Abdesol\\Documents//pyscreenrec_data'
```

and I am using the code below 
``` 
import pyscreenrec, time
recorder = pyscreenrec.ScreenRecorder()

recorder.start_recording('rec.mp4')

time.sleep(10)
print("Created")

recorder.stop_recording() 
```
I don't need that much help but I just need to show you this error
thanks

**Comment by Abdesol** [comment]
![image](https://user-images.githubusercontent.com/69455299/109335614-55bdb400-7873-11eb-86cd-93df2bf7f315.png)
I think the error is where the red mark is.

**Comment by Abdesol** [comment]
As I think you have to make a change in the 
https://github.com/Shravan-1908/pyscreenrec/blob/master/pyscreenrec/__init__.py file
line number 25 `self.screenshot_folder = os.path.join(os.path.expanduser("~"), "Documents//pyscreenrec_data")` to `self.screenshot_folder = os.path.join(os.path.expanduser("~"), "Documents\\pyscreenrec_data")`

**Comment by Abdesol** [comment]
I think this is not the only change you have to make. I have no deep knowledge of computer vision(open cv).
I tried changing that but not fixed, I tried to create pyscreenrec_data inside the documents folder and not working again, now showing another error the image is below:
![image](https://user-images.githubusercontent.com/69455299/109337084-57887700-7875-11eb-8c5c-3810ee2ed4b7.png)
I think you have to fix some other things on the root code.
Maybe it is from my PC firewall if so please tell me.
thanks

**Comment by Shravan-1908** [comment]
Thanks for posting an issue!

Can you please attach a screenshot of the `pyscreenrec_data` folder you created manually?

Also, execute the following code snippet:
```python
import os

directory = os.path.join(os.path.expanduser("~"), "Documents", "pyscreenrec_data")
print(os.path.exists(directory))
print(os.listdir(directory))
```
Please share the output of the above code. If the output is not `True` and a blank list(`[]`), then there's some issue with your system.

**Comment by Shravan-1908** [comment]
Is the issue fixed?
