### ISSUE TITLE
list index out of range for sample code

### ISSUE THREAD

**Issue by palash018** [shravanasati/pyscreenrec#5]
**Describe the bug**
Ran sample code given on Pypi on git bash in windows 11 got error.

**To Reproduce**
Run sample code given on Pypi 

**Expected behavior**
Recording should start and save

**Screenshots**
![image](https://github.com/user-attachments/assets/4d8827ac-3d89-4f5d-9892-364454526c0e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of pyscreenrec you are using : 0.5
 

**Additional context**
```
>>> import pyscreenrec
>>> recorder = pyscreenrec.ScreenRecorder()

>>> # to start recording
>>> recorder.start_recording("recording.mp4", 10) 
>>> # 'recording.mp4' is the name of the output video file, may also contain full path like 'C:/Users/<user>/Videos/video.mp4'
>>> # the second parameter(10) is the FPS. You can specify the FPS for the screen recording using the second parameter.

>>> # to pause recording
>>> recorder.pause_recording()

>>> # to resume recording
>>> recorder.resume_recording()

>>> # to stop recording
>>> recorder.stop_recording()
```

**Comment by shravanasati** [comment]
The sample code only outlines the API, it doesn't give the program any time to record the screen. Can you share the output after adding a `time.sleep(5)` call after the `start_recording` method? 

This calls for a better example usage snippet.

On another note, this needs to be fixed. A simple condition to check the length of images in the `stop_recording` method would fix this, but what should the behavior be? Should pyscreenrec raise an error or just silently ignore it and return?

**Comment by palash018** [comment]
```time.sleep()``` worked please introduce error for this as this may continue to be a common mistake

**Comment by shravanasati** [comment]
It's good to hear this was resolved. Thanks for reporting the issue. I'll consider adding an exception for such cases.
